# on:
#   release:
#     types: [created]
on:
  push:
    branches: [ "main" ]
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag dummy
        id=$(docker create dummy)
        VERSION=$(grep -m 1 version pyproject.toml | tr -s ' ' | tr -d '"' | tr -d "'" | cut -d' ' -f3)
        docker cp $id:/opt/pyfer/dist/python_ferret-${VERSION}-py3-none-any.whl python_ferret-${VERSION}-py3-none-any.whl
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: |
          *.whl
 