# on:
#   release:
#     types: [created]
on:
  push:
    branches: [ "main" ]
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag dummy:$(date +%s)
        id=$(docker create image-name)
        docker cp $id:/opt/pyfer pyferret-0.1.0-py3-none-any.whl /tmp/python_ferret-0.1.0-py3-none-any.whl
 