# on:
#   release:
#     types: [created]
on:
  push:
    branches: [ "main" ]
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag dummy
        id=$(docker create dummy)
        docker cp $id:/opt/pyfer/dist/python_ferret-0.2.1-py3-none-any.whl python_ferret-0.2.1-py3-none-any.whl
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: |
          python_ferret-0.2.1-py3-none-any.whl
 